server:
  port: 9527

spring:
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    time-zone: GMT+8

myapp:
  # /opt/project/phantomjs/genImage/temp/             ->  /app/data/temp/
  # /opt/project/phantomjs/genImage/server/           ->  /app/data/server/
  # /opt/project/phantomjs/genImage/echarts-convert/  ->  /app/data/echarts-convert/
  bucketNameForReport: "dzy-oss202503"
  ossPdfPath: "pdf/report/"
  outputPath: "/app/data/temp/img/"
  outputPdfPath: "/app/data/temp/pdf/"
  optionTempTxtPath: "/app/data/temp/txt/"
  phantomjsPath: "/app/data/server/bin/phantomjs"
  scriptPath: "/app/data/echarts-convert/echarts-convert.js"





